#tasks file for ansible-nagios-client

#- name: Deploy nagios-nrpe on client
#  tasks:
#- name: Create a group of all hosts by operating system 
#  group_by: key={{ansible_distribution}}
#- hosts: Ubuntu
#  user: root
#  - tasks:
#   - name: Copy apt sources.list file to client
#     copy: src=/etc/ansible/files/sources.list dest=/home/test/sources.list
#                owner=root group=root mode=0644
- include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include: Debian.yml
  when: ansible_distribution == 'Debian'
