
- name: Install nagios nrpe server
  apt: pkg={{ item }} update_cache=yes
  with_items:
  - nagios-nrpe-server
  - nagios-plugins-basic

- template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify:
    - restart nagios nrpe daemon
