
- name: Install nagios nrpe server
  apt: pkg={{ item }} update_cache=yes install_recommends=no cache_valid_time=600
  with_items:
  - nagios-nrpe-server

- template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify:
    - restart nagios nrpe daemon

- name: Check if plugins package is already installed
  stat: path="/usr/local/nagios/libexec/check_users"
  register: plugins

# Build and install nagios check plugins.
- tasks:
  include: build-plugins.yml
  when: not plugins.stat.exists
